filters:
- ahole,donuts
- anus,donuts
- ass,donuts
- Biatch,puppy
- bitch,puppy
- bitches,puppy
- c0ck,rooster
- Carpet Muncher,rooster
- cawk,rooster
- cawks,rooster
- Clit,peach
- cnts,peach
- cntz,peach
- cock,rooster
- crap,poo
- cum,bake brownies
- cunt,peach
- cunts,peaches
- cuntz,peaches
- dick,rooster
- dild0,rooster
- dild0s,rooster
- dildo,rooster
- f u c k,nono
- f u c k e r,nono
- fag,cigarette
- faigs,cigarette
- fuck,oh dear
- fuk,oh dear
- kunt,peach
- masterbate,bake brownies
- masterbates,bake brownies
- orafis,rooster
- peeenus,rooster
- peeenusss,rooster
- peenus,rooster
- pen1s,rooster
- penis,rooster
- penus,rooster
- penuus,rooster
- Phuc,oh dear
- Phuk,oh dear
- Sh!t,dumb
- sh1t,dumb
- shit,dumb
- Shyt,dumb
- vag1na,peach
- vullva,peach
- vulva,peach
- \blag,awesome
- rain,sunshine
- planet minecraft,another dimension
- planetminecraft,another dimension
filterexceptions:
- ambassador
- glass
- assume
- passing
- pass
- villager
- villagers
mute:
  permissions: mumblechat.canmute
saveplayerdata: true
usePexPrefix: false
channels:
  global:
    color: dark_green
    muteable: true
    alias: g
  staff:
    permissions: mumblechat.adminchannel
    color: green
    muteable: false
    filter: false
    alias: st
  diplo:
    permissions: mumblechat.diplochannel
    color: light_purple
    muteable: true
    alias: d
  help:
    color: aqua
    muteable: true
    alias: h
  trade:
    color: dark_aqua
    muteable: true
    alias: t
  troll:
    color: gray
    muteable: true
    alias: tr
  local:
    color: yellow
    muteable: true
    alias: l
    distance: 230
  noob:
    color: white
    mutable: true
    alias: n
    default: true
